### ISSUE TITLE
Doesn't clear the Protection history for me

### ISSUE THREAD

**Issue by DcR-NL** [LesFerch/ClearDefenderHistory#6]
Tried both scripts (single and every restart) on Windows 11 Pro 23H2, but my protection history isn't empty after a reboot. Am I doing something wrong?

Proof after a reboot:
![image](https://github.com/user-attachments/assets/f8518dce-8657-4a61-87c4-6bf3893fd20e)

**Comment by LesFerch** [comment]
My guess is that "Protected folder access blocked" is not logged the same as a virus/malware detection. I'll do some testing and see what can be done.

BTW, these messages may be caused by a legit app that just needs to be added to the allowed list. See [this tutorial](https://www.elevenforum.com/t/add-or-remove-allowed-apps-for-controlled-folder-access-in-windows-11.4028/).

**Comment by LesFerch** [comment]
What you can do in the meantime is boot into Safe Mode and delete the `Scans` folder:

1. Hold `Shift` while selecting `Restart` in Windows
2. Follow the prompts to get to a Command prompt
3. Delete the folder with the command: `rd /s /q "C:\ProgramData\Microsoft\Windows Defender\Scans"`

Now I just need to see if I can do the same thing with the script. Changing the current script to delete that folder did not work in my tests, presumably because the scheduled task is running after that folder gets locked down.

**Comment by LesFerch** [comment]
The script now also clears "Protected folder access blocked" history.
